// 錯誤碼總表（03-API契約.md §12）：前端用同一份對應中文訊息。

export const ErrorCode = {
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',
  VALIDATION: 'VALIDATION',
  NOT_FOUND: 'NOT_FOUND',
  MARKET_DAY_CLOSED: 'MARKET_DAY_CLOSED',
  CART_EMPTY: 'CART_EMPTY',
  LISTING_UNAVAILABLE: 'LISTING_UNAVAILABLE',
  LISTING_LIMIT_EXCEEDED: 'LISTING_LIMIT_EXCEEDED',
  INVITE_INVALID: 'INVITE_INVALID',
  PRODUCT_CODE_DUPLICATE: 'PRODUCT_CODE_DUPLICATE',
  PICKUP_CODE_NOT_FOUND: 'PICKUP_CODE_NOT_FOUND',
  ALREADY_PICKED_UP: 'ALREADY_PICKED_UP',
  INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',
  QUOTA_EXCEEDED: 'QUOTA_EXCEEDED',
  IMAGE_TOO_LARGE: 'IMAGE_TOO_LARGE',
  IMAGE_TYPE_UNSUPPORTED: 'IMAGE_TYPE_UNSUPPORTED',
  CONFLICT: 'CONFLICT',
  // ⚠️ 規格外（委託方 2026-09-20 指示）
  /** 攤商的上架品項數已達上限 */
  PRODUCT_LIMIT_REACHED: 'PRODUCT_LIMIT_REACHED',
  /** 全站攤商數已達上限 */
  STALL_LIMIT_REACHED: 'STALL_LIMIT_REACHED',
  /** 店家還沒確認這筆訂單 */
  NOT_CONFIRMED: 'NOT_CONFIRMED',
} as const

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode]

/** 統一錯誤回應格式（03 §前言） */
export interface ApiErrorBody {
  error: ErrorCode | string
  message?: string
  issues?: unknown[]
  /** LISTING_UNAVAILABLE / LISTING_LIMIT_EXCEEDED 時回傳受影響的 listing */
  listingIds?: string[]
  /** ALREADY_PICKED_UP 時回傳原本的取貨時間 */
  pickedUpAt?: string
}

/** 各錯誤碼對應的 HTTP 狀態 */
export const ERROR_HTTP_STATUS: Record<ErrorCode, number> = {
  UNAUTHENTICATED: 401,
  FORBIDDEN: 403,
  VALIDATION: 400,
  NOT_FOUND: 404,
  MARKET_DAY_CLOSED: 409,
  CART_EMPTY: 400,
  LISTING_UNAVAILABLE: 409,
  LISTING_LIMIT_EXCEEDED: 409,
  INVITE_INVALID: 400,
  PRODUCT_CODE_DUPLICATE: 409,
  PICKUP_CODE_NOT_FOUND: 404,
  ALREADY_PICKED_UP: 409,
  INVALID_STATE_TRANSITION: 409,
  QUOTA_EXCEEDED: 409,
  IMAGE_TOO_LARGE: 400,
  IMAGE_TYPE_UNSUPPORTED: 400,
  CONFLICT: 409,
  PRODUCT_LIMIT_REACHED: 409,
  STALL_LIMIT_REACHED: 409,
  NOT_CONFIRMED: 409,
}
